name: mcp_schema_runtime
resolution: workspace
description: Runtime metadata models and types for the Model Context Protocol (MCP) schema generator.
version: 1.0.0-beta.1
repository: https://github.com/rohit-chouhan/mcp_schema_generator
issue_tracker: https://github.com/rohit-chouhan/mcp_schema_generator/issues
topics:
  - mcp
  - metadata
  - ai

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
